CREATE OR REPLACE TRIGGER CHECK_CARGOMANIFEST_DATES_VALID
    BEFORE INSERT
    ON CARGOMANIFEST
    FOR EACH ROW
DECLARE
    DateStartBusy TIMESTAMP;
BEGIN
    SELECT CARGOMANIFEST.DATESTARTESTIMATED
    INTO DateStartBusy
    FROM CARGOMANIFEST
    WHERE CARGOMANIFEST.IDTRANSPORT = :NEW.IDTRANSPORT AND ROWNUM = 1 AND CARGOMANIFEST.IDCARGOMANIFESTTYPE = :NEW.IDCARGOMANIFESTTYPE AND (
        --Start Before AND Finish Between
        (:NEW.DATESTARTESTIMATED < CARGOMANIFEST.DATESTARTESTIMATED AND :NEW.DATEFINISHESTIMATED > CARGOMANIFEST.DATESTARTESTIMATED  AND :NEW.DATEFINISHESTIMATED < CARGOMANIFEST.DATEFINISHESTIMATED)
        OR--Start Before AND Finish After
        (:NEW.DATESTARTESTIMATED < CARGOMANIFEST.DATESTARTESTIMATED AND  :NEW.DATEFINISHESTIMATED > CARGOMANIFEST.DATEFINISHESTIMATED)
        OR--Start Between AND Finish After
        (:NEW.DATESTARTESTIMATED > CARGOMANIFEST.DATESTARTESTIMATED  AND :NEW.DATESTARTESTIMATED < CARGOMANIFEST.DATEFINISHESTIMATED AND :NEW.DATEFINISHESTIMATED > CARGOMANIFEST.DATEFINISHESTIMATED)
        OR--Start Between AND Finish Between
        (:NEW.DATESTARTESTIMATED > CARGOMANIFEST.DATESTARTESTIMATED AND :NEW.DATESTARTESTIMATED < CARGOMANIFEST.DATEFINISHESTIMATED AND :NEW.DATEFINISHESTIMATED > CARGOMANIFEST.DATESTARTESTIMATED AND :NEW.DATEFINISHESTIMATED < CARGOMANIFEST.DATESTARTESTIMATED)
        OR--Start is the same
        (:NEW.DATEFINISHESTIMATED = CARGOMANIFEST.DATEFINISHESTIMATED)
        OR--Finish  is the same
        (:NEW.DATESTARTESTIMATED = CARGOMANIFEST.DATESTARTESTIMATED)
        );
    IF DateStartBusy IS NOT NULL
    THEN
        RAISE_APPLICATION_ERROR(-20309, 'Ship is occupied. Ship has a cargo manifest starting at ' ||
                                        TO_CHAR(DateStartBusy, 'dd-MM-yyyy HH:mm') || '.');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DateStartBusy := NULL;
END;