DECLARE
    IN_CONTAINER_IDENTIFIER VARCHAR2(30);
    IN_CLIENT_IDENTIFIER NUMBER;
    OUT_RETURN_CODE NUMBER;
    OUT_RETURN_MSG VARCHAR2(100);

    BEGIN
    IN_CONTAINER_IDENTIFIER := 'CAIU9802647';
    IN_CLIENT_IDENTIFIER := 1;
    US312_CLIENT_CONTAINER_SITUATION(IN_CONTAINER_IDENTIFIER, IN_CLIENT_IDENTIFIER, OUT_RETURN_CODE, OUT_RETURN_MSG);
    DBMS_OUTPUT.PUT_LINE('RETURN CODE: ' || OUT_RETURN_CODE);
    DBMS_OUTPUT.PUT_LINE('RETURN MSG: ' || OUT_RETURN_MSG);
END;
