--PROCEDURE TO VERIFY IF A SPECIFIC CONTAINER EXISTS
CREATE OR REPLACE PROCEDURE CONTAINER_EXISTS(IN_CONTAINER_IDENTIFIER IN VARCHAR2, OUT_CONTAINER_EXISTS OUT BOOLEAN) AS BEGIN
DECLARE
RECORD_COUNT NUMBER;
BEGIN
    OUT_CONTAINER_EXISTS := FALSE;

    SELECT COUNT(*) INTO RECORD_COUNT FROM CONTAINER WHERE CONTAINER.IDENTIFICATIONNUMBER = IN_CONTAINER_IDENTIFIER;

    IF RECORD_COUNT > 0 THEN
        OUT_CONTAINER_EXISTS := TRUE;
    END IF;
END;
END;
