-- PROCEDURE TO OBTAIN THE CURRENT SITUATION OF A SPECIFIC CONTAINER(CONTAINS QUERY FROM US204)
CREATE OR REPLACE PROCEDURE GET_CONTAINER_CURRENT_SITUATION(IN_CONTAINER_IDENTIFIER IN VARCHAR2, OUT_LOCATION_TYPE OUT VARCHAR2, OUT_LOCATION_NAME OUT VARCHAR2, OUT_CONTAINER_CLIENT OUT NUMBER)
AS
BEGIN

SELECT
CASE
        WHEN CARGOMANIFESTTYPE.DESCRIPTION = 'Unload' AND CARGOMANIFEST.DATEFINISH IS NOT NULL THEN(
                SELECT CARGOSITE.NAME
                FROM CARGOSITE
                WHERE CARGOSITE.ID = CARGOMANIFEST.IDCARGOSITEDESTINATION
        )
        ELSE(
            SELECT
            CASE
                WHEN TRANSPORTTYPE.DESCRIPTION = 'Truck' THEN TRUCK.LICENSEPLATE
                ELSE SHIP.NAME
            END
            FROM TRANSPORT
            INNER JOIN TRANSPORTTYPE ON TRANSPORT.IDTRANSPORTTYPE = TRANSPORTTYPE.ID
            LEFT JOIN SHIP on TRANSPORT.ID = SHIP.IDTRANSPORT
            LEFT JOIN TRUCK on TRANSPORT.ID = TRUCK.IDTRANSPORT
            WHERE TRANSPORT.ID = CARGOMANIFEST.IDTRANSPORT
        )
    END LOCATION_NAME,
    CASE
        WHEN CARGOMANIFESTTYPE.DESCRIPTION = 'Unload' AND CARGOMANIFEST.DATEFINISH IS NOT NULL THEN(
            SELECT CARGOSITETYPE.DESCRIPTION
            FROM CARGOSITE
            INNER JOIN CARGOSITETYPE ON CARGOSITE.IDCARGOSITETYPE = CARGOSITETYPE.ID
            WHERE CARGOSITE.ID = CARGOMANIFEST.IDCARGOSITEDESTINATION
        )
        ELSE(
            SELECT
            TRANSPORTTYPE.DESCRIPTION
            FROM TRANSPORT
            INNER JOIN TRANSPORTTYPE ON TRANSPORT.IDTRANSPORTTYPE = TRANSPORTTYPE.ID
            WHERE TRANSPORT.ID = CARGOMANIFEST.IDTRANSPORT
        )
    END LOCATION_TYPE,
    CARGOMANIFESTLINE.IDLEASINGCLIENT
INTO OUT_LOCATION_NAME, OUT_LOCATION_TYPE, OUT_CONTAINER_CLIENT
FROM CARGOMANIFEST
INNER JOIN CARGOMANIFESTTYPE ON CARGOMANIFEST.IDCARGOMANIFESTTYPE = CARGOMANIFESTTYPE.ID
INNER JOIN CARGOMANIFESTLINE ON CARGOMANIFEST.ID = CARGOMANIFESTLINE.IDCARGOMANIFEST
INNER JOIN CONTAINER ON CARGOMANIFESTLINE.IDCONTAINER = CONTAINER.ID
WHERE CARGOMANIFEST.ID = ( -- GET LAST CARGO MANIFEST ASSOCIATED WITH CONTAINER
SELECT *
    FROM(
        SELECT CARGOMANIFESTLINE.IDCARGOMANIFEST
        FROM CARGOMANIFESTLINE
        INNER JOIN CARGOMANIFEST ON CARGOMANIFESTLINE.IDCARGOMANIFEST = CARGOMANIFEST.ID
        INNER JOIN CONTAINER ON CONTAINER.ID = CARGOMANIFESTLINE.IDCONTAINER
        WHERE CONTAINER.IDENTIFICATIONNUMBER = IN_CONTAINER_IDENTIFIER AND CARGOMANIFEST.DATESTART IS NOT NULL
        ORDER BY CARGOMANIFEST.DATESTART DESC, CARGOMANIFEST.ID DESC)
    WHERE ROWNUM = 1
) AND CONTAINER.IDENTIFICATIONNUMBER = IN_CONTAINER_IDENTIFIER;
END;
