-- MAIN PROCEDURE FOR US312. THIS PROCEDURE EXECUTES EVERYTHING TO OBTAIN THE RESULT FOR THE US
CREATE OR REPLACE PROCEDURE US312_CLIENT_CONTAINER_SITUATION(IN_CONTAINER_IDENTIFIER IN VARCHAR2, IN_CLIENT_IDENTIFIER IN NUMBER, OUT_RETURN_CODE OUT NUMBER, OUT_RETURN_MSG OUT VARCHAR2) AS BEGIN
DECLARE
OUT_LOCATION_TYPE VARCHAR2(30);
OUT_LOCATION_NAME VARCHAR2(30);
OUT_CONTAINER_CLIENT NUMBER;
OUT_CONTAINER_EXISTS BOOLEAN;
BEGIN
     OUT_RETURN_CODE := 0;

     CONTAINER_EXISTS(IN_CONTAINER_IDENTIFIER, OUT_CONTAINER_EXISTS);

     --VALIDATE IF CONTAINER ID EXISTS
     IF NOT OUT_CONTAINER_EXISTS THEN
         OUT_RETURN_CODE := 10;
         OUT_RETURN_MSG := 'Invalid container ID';
         RETURN;
     END if;

     GET_CONTAINER_CURRENT_SITUATION(IN_CONTAINER_IDENTIFIER, OUT_LOCATION_TYPE, OUT_LOCATION_NAME, OUT_CONTAINER_CLIENT);

     IF(OUT_LOCATION_TYPE IS NULL AND OUT_LOCATION_NAME IS NULL) THEN
          OUT_RETURN_CODE := 0;
          OUT_RETURN_MSG := 'At the moment there is no CARGO MANIFEST associated with that specific container';
          RETURN;
     END IF;

    IF OUT_CONTAINER_CLIENT IS NULL OR IN_CLIENT_IDENTIFIER != OUT_CONTAINER_CLIENT THEN
         OUT_RETURN_CODE := 11;
         OUT_RETURN_MSG := 'Container is not leased by client';
         RETURN;
    END IF;

     OUT_RETURN_CODE:= 1;
     OUT_RETURN_MSG := 'Container is on a ' || OUT_LOCATION_TYPE || ' with the name: ' || OUT_LOCATION_NAME;
END;
END;
