SELECT
CASE
    WHEN CARGOMANIFESTTYPE.DESCRIPTION = 'Unload' AND CARGOMANIFEST.DATEFINISH IS NOT NULL THEN(
            SELECT CARGOSITE.NAME
            FROM CARGOSITE
            WHERE CARGOSITE.ID = CARGOMANIFEST.IDCARGOSITEDESTINATION
    )
    ELSE(
        SELECT
        CASE
            WHEN TRANSPORTTYPE.DESCRIPTION = 'Truck' THEN TRUCK.LICENSEPLATE
            ELSE SHIP.NAME
        END
        FROM TRANSPORT
        INNER JOIN TRANSPORTTYPE ON TRANSPORT.IDTRANSPORTTYPE = TRANSPORTTYPE.ID
        LEFT JOIN SHIP on TRANSPORT.ID = SHIP.IDTRANSPORT
        LEFT JOIN TRUCK on TRANSPORT.ID = TRUCK.IDTRANSPORT
        WHERE TRANSPORT.ID = CARGOMANIFEST.IDTRANSPORT
    )
END LOCATION_NAME,
CASE
    WHEN CARGOMANIFESTTYPE.DESCRIPTION = 'Unload' AND CARGOMANIFEST.DATEFINISH IS NOT NULL THEN(
        SELECT CARGOSITETYPE.DESCRIPTION
        FROM CARGOSITE
        INNER JOIN CARGOSITETYPE ON CARGOSITE.IDCARGOSITETYPE = CARGOSITETYPE.ID
        WHERE CARGOSITE.ID = CARGOMANIFEST.IDCARGOSITEDESTINATION
    )
    ELSE(
        SELECT
        TRANSPORTTYPE.DESCRIPTION
        FROM TRANSPORT
        INNER JOIN TRANSPORTTYPE ON TRANSPORT.IDTRANSPORTTYPE = TRANSPORTTYPE.ID
        WHERE TRANSPORT.ID = CARGOMANIFEST.IDTRANSPORT
    )
END LOCATION_TYPE
FROM CARGOMANIFEST
INNER JOIN CARGOMANIFESTTYPE ON CARGOMANIFEST.IDCARGOMANIFESTTYPE = CARGOMANIFESTTYPE.ID
WHERE CARGOMANIFEST.ID = ( -- GET LAST CARGO MANIFEST ASSOCIATED WITH CONTAINER
SELECT *
    FROM(
        SELECT CARGOMANIFESTLINE.IDCARGOMANIFEST
        FROM CARGOMANIFESTLINE
        INNER JOIN CARGOMANIFEST ON CARGOMANIFESTLINE.IDCARGOMANIFEST = CARGOMANIFEST.ID
        INNER JOIN CONTAINER ON CONTAINER.ID = CARGOMANIFESTLINE.IDCONTAINER
        WHERE CONTAINER.IDENTIFICATIONNUMBER = ? AND CARGOMANIFEST.DATESTART IS NOT NULL
        ORDER BY CARGOMANIFEST.DATESTART DESC, CARGOMANIFEST.ID DESC)
    WHERE ROWNUM = 1
)