
SELECT CARGOSITE.NAME                                       AS Cargo_Site_Name,
       CARGOSITETYPE.DESCRIPTION                            AS Cargo_Site_Type,
       COUNTRY.DESCRIPTION                                  AS Cargo_Site_Country,
       CONTAINER.IDENTIFICATIONNUMBER                       AS Container_ID,
       CONTAINER.TEMPERATURE                                AS Container_Type,
       CARGOMANIFESTLINE.GROSSWEIGHT - CONTAINER.TAREWEIGHT AS Container_Load

FROM CONTAINER
         INNER JOIN CARGOMANIFESTLINE ON CONTAINER.ID = CARGOMANIFESTLINE.IDCONTAINER
         INNER JOIN CARGOMANIFEST ON CARGOMANIFESTLINE.IDCARGOMANIFEST = CARGOMANIFEST.ID
         INNER JOIN CARGOSITE ON CARGOMANIFEST.IDCARGOSITEDESTINATION = CARGOSITE.ID
         INNER JOIN CARGOSITETYPE ON CARGOSITE.IDCARGOSITETYPE = CARGOSITETYPE.ID
         INNER JOIN COUNTRY ON CARGOSITE.IDCOUNTRY = COUNTRY.ID

WHERE CARGOMANIFESTLINE.IDCARGOMANIFEST IN (
    SELECT CARGOMANIFEST.ID

    FROM CARGOMANIFEST
             INNER JOIN SHIP ON CARGOMANIFEST.IDTRANSPORT = SHIP.IDTRANSPORT
             INNER JOIN CARGOMANIFESTTYPE ON CARGOMANIFEST.IDCARGOMANIFESTTYPE = CARGOMANIFESTTYPE.ID
             INNER JOIN CARGOSITE ON CARGOMANIFEST.IDCARGOSITEDESTINATION = CARGOSITE.ID
             INNER JOIN CARGOSITETYPE ON CARGOSITE.IDCARGOSITETYPE = CARGOSITETYPE.ID

    WHERE CARGOMANIFEST.DATESTART IS NULL
      AND CARGOMANIFESTTYPE.DESCRIPTION = 'Load'
      AND CARGOSITETYPE.DESCRIPTION = 'Port'
      AND SHIP.MMSI = ?
    ORDER BY CARGOMANIFEST.DATESTARTESTIMATED ASC
        FETCH FIRST 1 ROW ONLY
)