SELECT  TRUNC((Loaded.Percentage - Unloaded.Percentage)*100) AS OccupancyPercentage
FROM (
     SELECT NVL(SUM(COUNT(CARGOMANIFESTLINE.IDCONTAINER)/TO_NUMBER(SHIP.CAPACITY)), 0) AS Percentage
     FROM CARGOMANIFEST
              INNER JOIN CARGOMANIFESTLINE ON CARGOMANIFESTLINE.IDCARGOMANIFEST = CARGOMANIFEST.ID
              INNER JOIN TRANSPORT ON TRANSPORT.ID = CARGOMANIFEST.IDTRANSPORT
              INNER JOIN SHIP ON TRANSPORT.ID = SHIP.IDTRANSPORT
              INNER JOIN CARGOMANIFESTTYPE ON CARGOMANIFEST.IDCARGOMANIFESTTYPE = CARGOMANIFESTTYPE.ID
     WHERE TRANSPORT.ID = ? AND CARGOMANIFESTTYPE.DESCRIPTION = 'Load'  AND CARGOMANIFEST.DATESTART <= ?
     GROUP BY SHip.CAPACITY) Loaded
 LEFT JOIN (
    SELECT NVL(SUM(COUNT(CARGOMANIFESTLINE.IDCONTAINER)/TO_NUMBER(SHIP.CAPACITY)), 0) AS Percentage
    FROM CARGOMANIFEST
             INNER JOIN CARGOMANIFESTLINE ON CARGOMANIFESTLINE.IDCARGOMANIFEST = CARGOMANIFEST.ID
             INNER JOIN TRANSPORT ON TRANSPORT.ID = CARGOMANIFEST.IDTRANSPORT
             INNER JOIN SHIP ON TRANSPORT.ID = SHIP.IDTRANSPORT
             INNER JOIN CARGOMANIFESTTYPE ON CARGOMANIFEST.IDCARGOMANIFESTTYPE = CARGOMANIFESTTYPE.ID
    WHERE TRANSPORT.ID = ? AND CARGOMANIFESTTYPE.DESCRIPTION = 'Unload' AND CARGOMANIFEST.DATEFINISH <= ?
    GROUP BY SHip.CAPACITY) Unloaded ON 1=1