SELECT COUNT(DISTINCT CM.ID) AS CARGOMANIFESTNUMBER, AVG(COUNT(CML.IDCONTAINER)) AS CONTAINERAVERAGE
FROM CARGOMANIFEST CM
    INNER JOIN CARGOMANIFESTTYPE CMT ON CMT.ID = CM.IDCARGOMANIFESTTYPE
    INNER JOIN CARGOMANIFESTLINE CML ON CML.IDCARGOMANIFEST = CM.ID
WHERE CMT.DESCRIPTION='Load' AND EXTRACT(YEAR FROM CM.DATEFINISH) = EXTRACT(YEAR FROM ?)
group by CM.ID