SELECT CARGOSITE.LATITUDE, CARGOSITE.LONGITUDE, NAME AS PORT_NAME, COUNTRY.DESCRIPTION AS PORT_COUNTRY, COUNTRY.IDCONTINENT AS PORT_CONTINENT
FROM CARGOSITE
INNER JOIN CARGOSITETYPE ON CARGOSITE.IDCARGOSITETYPE = CARGOSITETYPE.ID
INNER JOIN COUNTRY ON CARGOSITE.IDCOUNTRY = COUNTRY.DESCRIPTION
WHERE CARGOSITETYPE.DESCRIPTION =  'Port'