SELECT CARGOSITE.IDCOUNTRY AS FROM_COUNTRY, CARGOSITE.NAME AS FROM_PORT, C2.IDCOUNTRY AS TO_COUNTRY, C2.NAME AS TO_PORT, DISTANCE FROM SEADIST
INNER JOIN CARGOSITE ON SEADIST.IDCARGOSITEFROM = CARGOSITE.ID
INNER JOIN CARGOSITE C2 ON SEADIST.IDCARGOSITETO = C2.ID