SELECT
    SHIP.MMSI SHIPMMSI, SHIP.NAME SHIPNAME, LOCATION.Name LOCATIONDESCRIPTION, LOCATION.LONGITUDE LOCATIONLONGITUDE, LOCATION.LATITUDE LOCATIONLATITUDE
FROM SHIP ,
     (
         SELECT CARGOSITE.NAME, CARGOSITE.LATITUDE, CARGOSITE.LONGITUDE, CARGOMANIFEST.IDTRANSPORT,
            ROW_NUMBER() OVER (PARTITION BY CARGOMANIFEST.IDTRANSPORT ORDER BY CARGOMANIFEST.DATEFINISHESTIMATED DESC) FIRST
         FROM CARGOMANIFEST
          INNER JOIN CARGOSITE ON CARGOMANIFEST.IDCARGOSITEDESTINATION = CARGOSITE.ID
         WHERE CARGOMANIFEST.DATEFINISHESTIMATED <= TO_TIMESTAMP(NEXT_DAY(SYSDATE, 'SEG'))
     ) LOCATION
WHERE
    LOCATION.IDTRANSPORT  = SHIP.IDTRANSPORT AND
    FIRST = 1 AND
    SHIP.IDTRANSPORT NOT IN (
        SELECT TRANSPORT.ID
        FROM TRANSPORT
        INNER JOIN CARGOMANIFEST ON TRANSPORT.ID = CARGOMANIFEST.IDTRANSPORT
        INNER JOIN TRANSPORTTYPE ON TRANSPORT.IDTRANSPORTTYPE = TRANSPORTTYPE.ID
        WHERE TRANSPORTTYPE.DESCRIPTION = 'Ship' AND CARGOMANIFEST.DATESTARTESTIMATED <= TO_TIMESTAMP(NEXT_DAY(SYSDATE,'SEG'))
        AND CARGOMANIFEST.DATEFINISHESTIMATED >= TO_TIMESTAMP(NEXT_DAY(SYSDATE, 'SEG'))
)