CREATE OR REPLACE PROCEDURE GET_OCCUPANCYRATE(IN_SHIPMMSI_ID IN NUMBER, IN_CARGOMANIFEST_ID NUMBER, OUT_OCCUPANCY_RATE OUT DECIMAL)
AS
BEGIN
    SELECT ((COUNT(CARGOMANIFESTLINE.IDCONTAINER)/TO_NUMBER(SHIP.CAPACITY)*100 ))  INTO OUT_OCCUPANCY_RATE -- CALCULATION IS PERFORMED AS OCCUPANCYRATE/TOTAL CAPACITY OF SHIP
    FROM CARGOMANIFEST
    INNER JOIN CARGOMANIFESTLINE ON CARGOMANIFESTLINE.IDCARGOMANIFEST = CARGOMANIFEST.ID
    INNER JOIN TRANSPORT ON TRANSPORT.ID = CARGOMANIFEST.IDTRANSPORT
    INNER JOIN SHIP on TRANSPORT.ID = SHIP.IDTRANSPORT
    WHERE SHIP.MMSI = IN_SHIPMMSI_ID AND CARGOMANIFEST.ID = IN_CARGOMANIFEST_ID -- FILTER BY SHIP MMSI AND CARGOMANIFEST ID
    GROUP BY SHIP.CAPACITY;
END;
