DECLARE
US406_RETURN_CURSOR SYS_REFCURSOR;
SHIP_MMSI SHIP.MMSI%type;
DESTINATION_CARGOSITE CARGOSITE.NAME%type;
DEPARTURE_CARGOSITE CARGOSITE.NAME%type;
DATE_START CARGOMANIFEST.DATESTART%type;
DATE_FINISH CARGOMANIFEST.DATEFINISH%type;
AVERAGE_OCCUPANCY_RATE DECIMAL;

BEGIN
    -- THIS CURSOR SHOULD RETURN 4 TRIPS WITH
    -- AVERAGE OCCUPANCY RATE BELLOW THE THRESHOLD OF 66%
    US406_RETURN_CURSOR := US406();

    DBMS_OUTPUT.PUT_LINE('THIS CURSOR SHOULD ONLY RETURN 4 TRIPS WITH AN AVERAGE OCCUPANCY RATE BELLOW THE THRESHOLD OF 66%' || chr(10) || '_____');

    LOOP
       FETCH US406_RETURN_CURSOR INTO SHIP_MMSI, DESTINATION_CARGOSITE, DEPARTURE_CARGOSITE, DATE_START, DATE_FINISH, AVERAGE_OCCUPANCY_RATE;

        EXIT WHEN US406_RETURN_CURSOR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('SHIP WITH MMSI ' || SHIP_MMSI || ' HAD A VOYAGE FROM ' || DEPARTURE_CARGOSITE || ' TO ' || DESTINATION_CARGOSITE || ' THAT STARTED ON : ' || DATE_START || ' AND ENDED ON: ' || DATE_FINISH || ' WHICH HAD AN AVERAGE OCCUPANCY RATE OF ' || AVERAGE_OCCUPANCY_RATE || '% WHICH IS BELLOW THE TRESHOLD OF 66%');
       END LOOP;

    CLOSE US406_RETURN_CURSOR;
    DBMS_OUTPUT.PUT_LINE('_____' || chr(10));

    -- ARTIFICIALLY UPDATE SHIP CAPACITY TO 5
    -- FOR SHIP WITH MMSI 212180000 IN ORDER TO
    -- TO INCREASE OVERALL AVERAGE OCCUPANCY RATE WHEN IT GETS CALCULATED
    UPDATE SHIP
    SET CAPACITY = 5
    WHERE MMSI = 212180000;

    -- AFTER THE PREVIOUS UPDATE, THIS CURSOR
    -- SHOULD ONLY RETURN 3 TRIPS WITH AN
    -- AVERAGE OCCUPANCY RATE BELLOW 66%
    US406_RETURN_CURSOR := US406();

    DBMS_OUTPUT.PUT_LINE('THIS CURSOR SHOULD ONLY RETURN 3 TRIPS WITH AN AVERAGE OCCUPANCY RATE BELLOW THE THRESHOLD OF 66%' || chr(10) || '_____');

    LOOP
       FETCH US406_RETURN_CURSOR INTO SHIP_MMSI, DESTINATION_CARGOSITE, DEPARTURE_CARGOSITE, DATE_START, DATE_FINISH, AVERAGE_OCCUPANCY_RATE;

        EXIT WHEN US406_RETURN_CURSOR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('SHIP WITH MMSI ' || SHIP_MMSI || ' HAD A VOYAGE FROM ' || DEPARTURE_CARGOSITE || ' TO ' || DESTINATION_CARGOSITE || ' THAT STARTED ON : ' || DATE_START || ' AND ENDED ON: ' || DATE_FINISH || ' WHICH HAD AN AVERAGE OCCUPANCY RATE OF ' || AVERAGE_OCCUPANCY_RATE || '% WHICH IS BELLOW THE TRESHOLD OF 66%');
       END LOOP;

    CLOSE US406_RETURN_CURSOR;

    DBMS_OUTPUT.PUT_LINE('_____' || chr(10));
    -- RESET SHIP CAPACITY
    UPDATE SHIP
    SET CAPACITY = 100
    WHERE MMSI = 212180000;
END;
