--VERIFIES IF A SPECIFIC GLOBAL TEMPORARY TABLE EXISTS FOR THE CURRENT USER
CREATE OR REPLACE FUNCTION VERIFY_GLOBAL_TEMPORARY_TABLE_EXISTS(IN_TABLE_NAME IN VARCHAR2) RETURN BOOLEAN
IS
NUM NUMBER;
BEGIN
    SELECT COUNT(*) INTO NUM FROM USER_TABLES WHERE TABLE_NAME = IN_TABLE_NAME;

    IF NUM > 0 THEN
        RETURN TRUE;
    END IF;
    RETURN FALSE;
END;
