-- GET'S ALL FINISHED TRIPS FOR ALL SHIPS
CREATE OR REPLACE FUNCTION GET_ALL_FINISHEDTRIPS RETURN SYS_REFCURSOR
IS
RETURN_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RETURN_CURSOR FOR
        SELECT SHIP.MMSI, DESTINATION_CARGOSITE.NAME, DEPARTURE_CARGOSITE.NAME, CARGOMANIFEST.DATESTART, CARGOMANIFEST.DATEFINISH FROM CARGOMANIFEST
        INNER JOIN TRANSPORT ON TRANSPORT.ID = CARGOMANIFEST.IDTRANSPORT
        INNER JOIN CARGOSITE DESTINATION_CARGOSITE ON CARGOMANIFEST.IDCARGOSITEDESTINATION = DESTINATION_CARGOSITE.ID
        INNER JOIN CARGOSITE DEPARTURE_CARGOSITE ON CARGOMANIFEST.IDCARGOSITEORIGIN = DEPARTURE_CARGOSITE.ID
        INNER JOIN SHIP on SHIP.IDTRANSPORT = TRANSPORT.ID
        INNER JOIN CARGOMANIFESTTYPE ON CARGOMANIFEST.IDCARGOMANIFESTTYPE = CARGOMANIFESTTYPE.ID
        AND DATESTART IS NOT NULL AND DATEFINISH IS NOT NULL-- FILTER BY TRIPS THAT HAVE ALREADY FINISHED
        AND CARGOMANIFESTTYPE.DESCRIPTION = 'Load' -- FILTER BY CARGOMANIFEST'S OF TYPE LOAD, THEREFORE ONLY ACCOUNT FOR CARGOMANIFEST'S THAT REQUIRE A SHARE OF THE SHIP'S CAPACITY;
        ORDER BY SHIP.MMSI;

    RETURN RETURN_CURSOR;
END;
